language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
    - CI=true
    - secure: tyErps9rJ1EAAv/uVXyRIyl1iIrKg5hThDQLeImWiOBzVUqjr8ts081yFR+fiMPjEp2K4GGolvnhXaoYiWbNFqfDWbLCZHU3i+L5LkxAB5P/fbsIMkfL4EyvBzm9uq9+S6dVpp5c5CAKWzui3rMP2pjgrq1sCVx+nNxyKClc5HrpPvARIx58WLZd2hhBCwowV3xDZCbwJm1IaAai82zEwj04cVfkbASHG0rE5SxS+Qa1wD8YHv9t0w0yIQUCCHiQ5vkUu9/8Kh39nGrdcCVouAj4kxwtUgRnfk3N/Srsgbmf5TiUKw2SMNDI6j5gIk1Z2M7sVpxb7D9OLWjoAn/JQ7UYxAnIqaHUAJFkBqGX7hAdVxZImsfxL/9r6HPW7jEaMYiCsXeoIDUkEdxnQVP891S5Vucrd08gpfYlqZS7BX1m2ckxYLzfN7bO/c/TOOoLG5lP7QEwHBmla3DhHucrjRJgOYsqasftCmrJChHKdyNpz4a+WN1LyQqM1MXrLxO6QuNEcKF7WI14TqAdURcwUyHL/C96z28wTmvdGUrRT4Xc8RlEaGzhu737c7YR1OvGZ0DPcvCbT+A4wq0XZnHRtKG9K0Xde4/2WpjcDcVj1ye/MjtiyL2u2lT6W2FwDAy4pvZ5X5vgmhuyOMArNblzqjU7a2IOlW/ivGtNbHMgNqc=
    - secure: M+MLsEeWFSfs56uISa1QeZPfLv1raW3UVVu95Mn2fLUMLLueN1C6VpbK3GAJw9/3IW6c+HqZXObGSM8izBX8hx/gFl2j0jVWYTNpIw6TacI4TJ5qdcmNh3z4K9TJwSYQNeikbw8+IFprZSUvlgmwMMb96x2lcBWhc+n/VRDSUCac8Td3AGDxnZVTq9o05tjktf1m5eGqCbZ5PYMUAh3wMp27G4ctiYy5W2XAJ1gm6CpPtaNSTjJiD/7ZV+4DiU8EFMDMwll16AuNzgHxvxY+BoDzoXJFdYWOvQUwCHIsffdlJl2/qs49C+azoVt6PnP3s9w9GPIQOHJz2lKCG17CmSm3OG2zd7EtUsDVRBiyPgb5K4bAWNP6zhTyJLF44sc57kjrgmsevHNUdfc/lwe8MgydbmUV8EONw7XGXmbCU1NLcrPLhRUqJ0xq39FRFPQdl3tlCAwIC76vQzQbgmAib2S6XZg4Qr3+5RwJ0K7AxERPtaxbYOwsZhIVIdAzFFbUi14l+zZsCytiRR4wnUpMsMSA/4dvCrwvoypjfM1ecjhCJi1nzaJcjL9nDwr/NWl07xYtw9qmXhCICirWfZqgepLgVCvPp9NsVoMxxO3mQ6Ccpo1cW3nYyokp30TqOoxJTVl3jzglQy4k3xk/ZBoIAqYX3IghlhTcte8d1e4i304=
  matrix:
    - SAUCE_TIMEZONE=Tokyo
    - SAUCE_TIMEZONE=Moscow
